/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.25.2.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./P2PTrading.types";
import * as _1 from "./P2PTrading.client";
import * as _2 from "./P2PTrading.message-composer";
export namespace contracts {
  export const P2PTrading = { ..._0,
    ..._1,
    ..._2
  };
}